services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend/db:/app/db
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=2807
    networks:
      - transcendence-network

  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend-dist:/tmp
    command: sh -c "cp -r /usr/share/nginx/html/* /tmp/ && echo 'Frontend files copied' && sleep infinity"
    networks:
      - transcendence-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend
      - frontend-builder
    restart: unless-stopped
    volumes:
      - frontend-dist:/usr/share/nginx/html
    networks:
      - transcendence-network

volumes:
  frontend-dist:

networks:
  transcendence-network:
    driver: bridge
