services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "2807:2807"
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped