version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "2807:2807"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./backend/db:/app/db
      - ./backend/uploads:/app/uploads
      - ./backend/cert:/app/cert

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend/cert:/app/cert